---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/products
  label: Products
  create: all
  match: "**/*"
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":year/:month:/:filename:"
version: 0.38.1
